## Final Project Submission

Please fill out:
* Student name: 
* Student pace: self paced / part time / full time
* Scheduled project review date/time: 
* Instructor name: 
* Blog post URL:

# TMDB Dataset

In [43]:
# Your code here - remember to use markdown cells for comments as well!
import pandas as pd

In [44]:
tmdb = pd.read_csv('zippedData/tmdb.movies.csv.gz')

In [45]:
tmdb.head(20)

,Unnamed: 0,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count
0,0,"[12, 14, 10751]",12444,en,Harry Potter and the Deathly Hallows: Part 1,33.533,2010-11-19,Harry Potter and the Deathly Hallows: Part 1,7.7,10788
1,1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610
2,2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368
3,3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174
4,4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186
5,5,"[12, 14, 10751]",32657,en,Percy Jackson & the Olympians: The Lightning T...,26.691,2010-02-11,Percy Jackson & the Olympians: The Lightning T...,6.1,4229
6,6,"[28, 12, 14, 878]",19995,en,Avatar,26.526,2009-12-18,Avatar,7.4,18676
7,7,"[16, 10751, 35]",10193,en,Toy Story 3,24.445,2010-06-17,Toy Story 3,7.7,8340
8,8,"[16, 10751, 35]",20352,en,Despicable Me,23.673,2010-07-09,Despicable Me,7.2,10057
9,9,"[16, 28, 35, 10751, 878]",38055,en,Megamind,22.855,2010-11-04,Megamind,6.8,3635
10,10,"[16, 35, 10751]",863,en,Toy Story 2,22.698,1999-11-24,Toy Story 2,7.5,7553
11,11,"[10751, 14, 12]",12155,en,Alice in Wonderland,22.020,2010-03-05,Alice in Wonderland,6.6,8713
12,12,"[53, 12, 28]",27578,en,The Expendables,21.517,2010-08-03,The Expendables,6.1,4647
13,13,"[16, 10751]",38757,en,Tangled,21.511,2010-11-24,Tangled,7.5,6407
14,14,"[27, 80]",41439,en,Saw 3D,20.370,2010-10-28,Saw: The Final Chapter,6.0,1488
15,15,"[12, 14, 18, 10749]",24021,en,The Twilight Saga: Eclipse,20.340,2010-06-23,The Twilight Saga: Eclipse,6.0,4909
16,16,"[28, 53, 878]",20504,en,The Book of Eli,18.985,2010-01-11,The Book of Eli,6.7,3495
17,17,"[10402, 10749]",52371,nl,LelleBelle,18.586,2010-10-09,LelleBelle,4.5,36
18,18,"[28, 18, 53]",2502,en,The Bourne Supremacy,18.199,2004-07-23,The Bourne Supremacy,7.3,4367
19,19,"[18, 53, 9648]",11324,en,Shutter Island,18.060,2010-02-18,Shutter Island,8.1,12625

In [46]:
genres = {'28':"Action",
'12':"Adventure",
'16':"Animation",
'35':"Comedy",
'80':"Crime",
'99':"Documentary",
'18':"Drama",
'10751':"Family",
'14':"Fantasy",
'36':"History",
'27':"Horror",
'10402':"Music",
'9648':"Mystery",
'10749':"Romance",
'878':"Science Fiction",
'10770':"TV Movie",
'53':"Thriller",
'10752':"War",
'37':"Western"}

In [47]:
#tmdb['genre_ids'].map(genres)
tmdb = tmdb.replace(pd.Series(genres).astype(str), regex=True)

In [48]:
tmdb.head(20)

,Unnamed: 0,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count
0,0,"[Adventure, Fantasy, Family]",12444,en,Harry Potter and the Deathly Hallows: Part 1,33.533,2010-11-19,Harry Potter and the Deathly Hallows: Part 1,7.7,10788
1,1,"[Fantasy, Adventure, Animation, Family]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610
2,2,"[Adventure, Action, Science Fiction]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368
3,3,"[Animation, Comedy, Family]",862,en,Toy Story,28.005,1Documentary5-11-22,Toy Story,7.9,10174
4,4,"[Action, Science Fiction, Adventure]",27205,en,Inception,27.920,2010-07-Animation,Inception,8.3,22186
5,5,"[Adventure, Fantasy, Family]",32657,en,Percy Jackson & the Olympians: The Lightning T...,26.691,2010-02-11,Percy Jackson & the Olympians: The Lightning T...,6.1,4229
6,6,"[Action, Adventure, Fantasy, Science Fiction]",19995,en,Avatar,26.526,2009-Adventure-Drama,Avatar,7.4,18676
7,7,"[Animation, Family, Comedy]",10193,en,Toy Story 3,24.445,2010-06-17,Toy Story 3,7.7,8340
8,8,"[Animation, Family, Comedy]",20352,en,Despicable Me,23.673,2010-07-09,Despicable Me,7.2,10057
9,9,"[Animation, Action, Comedy, Family, Science Fi...",38055,en,Megamind,22.855,2010-11-04,Megamind,6.8,3635
10,10,"[Animation, Comedy, Family]",863,en,Toy Story 2,22.698,1Documentary9-11-24,Toy Story 2,7.5,7553
11,11,"[Family, Fantasy, Adventure]",12155,en,Alice in Wonderland,22.020,2010-03-05,Alice in Wonderland,6.6,8713
12,12,"[Thriller, Adventure, Action]",27578,en,The Expendables,21.517,2010-08-03,The Expendables,6.1,4647
13,13,"[Animation, Family]",38757,en,Tangled,21.511,2010-11-24,Tangled,7.5,6407
14,14,"[Horror, Crime]",41439,en,Saw 3D,20.370,2010-10-Action,Saw: The Final Chapter,6.0,1488
15,15,"[Adventure, Fantasy, Drama, Romance]",24021,en,The Twilight Saga: Eclipse,20.340,2010-06-23,The Twilight Saga: Eclipse,6.0,4909
16,16,"[Action, Thriller, Science Fiction]",20504,en,The Book of Eli,18.985,2010-01-11,The Book of Eli,6.7,3495
17,17,"[Music, Romance]",52371,nl,LelleBelle,18.586,2010-10-09,LelleBelle,4.5,36
18,18,"[Action, Drama, Thriller]",2502,en,The Bourne Supremacy,18.199,2004-07-23,The Bourne Supremacy,7.3,4367
19,19,"[Drama, Thriller, Mystery]",11324,en,Shutter Island,18.060,2010-02-Drama,Shutter Island,8.1,12625